name: CI - Full test suite

on:
  pull_request:
    branches:
      - '**'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup pnpm
            uses: pnpm/action-setup@v4
            with:
              version: 9.5.0
          - name: Setup node
            uses: actions/setup-node@v4
            with:
              node-version: 20.x
              cache: 'pnpm'
          - name: Install dependencies
            run: pnpm install --frozen-lockfile

          - name: Run detailed tests
            env:
              NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
              NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            run: pnpm run test:all
